### ISSUE TITLE
Versions 4.50 and later are missing

### ISSUE THREAD

**Issue by mschmidt-name** [TeXShop/TeXShop#2]
The last version committed is 4.44 and last tagged release is 4.18. It would be nice to get this repo up-to-date.

**Comment by fingolfin** [comment]
I have those archives, I'll look into running my scripts to import them.

Ideally there should be a GitHub Workflow which runs the necessary scripts to check for updates and imports them into the repository.

**Comment by fingolfin** [comment]
Hmm, actually it seems 4.54 and 4.55 are missing in my collection (and also 4.56, but that was quickly withdrawn, so may as well skip it).

**Comment by mschmidt-name** [comment]
It seems version 4.54 was only available for less than 1 hour:
- 4.54 announcement: https://tug.org/pipermail/macostex-archives/2020-December/057477.html
- 4.54 retraction: https://tug.org/pipermail/macostex-archives/2020-December/057478.html (reason was probably https://tex.stackexchange.com/questions/574514/texshop-one-window-mode-not-working-after-update-to-version-4-54)

Version 4.55 was only available for less than 1 day:
- 4.55 announcement: https://tug.org/pipermail/macostex-archives/2020-December/057479.html
- 4.56 announcement: https://tug.org/pipermail/macostex-archives/2020-December/057480.html

But version 4.56 was retracted less than 1 hour after announcement:
- 4.56 retraction: https://tug.org/pipermail/macostex-archives/2020-December/057481.html
- 4.57 announcement: https://tug.org/pipermail/macostex-archives/2020-December/057489.html

I guess your scripts didn't have enough time to download those versions and the question is if the source archives were also reverted after the retractions.

**Comment by fingolfin** [comment]
I've updated the git repository up to 5.15 now (with 4.54/4.55/4.56 missing).

Uploading the missing release artifacts is in progress but I am currently on slow internet, so it'll take some time...

**Comment by fingolfin** [comment]
Actually I made a mistake and skipped 4.79 :-( so I'll fix that now

**Comment by fingolfin** [comment]
Resolved

**Comment by fingolfin** [comment]
@mschmidt-name it seems my cron job missed version 5.17 (despite running once per hour?). Do you happen to know if it was also short lived or alternatively, have a copy around?

**Comment by mschmidt-name** [comment]
Thanks for uploading the previously missing versions!

Version 5.17 was never released. Richard decided to wait with the release and then bumped the version to 5.18 after including another feature. I agree, it is not clear from the Changes document.

**Comment by fingolfin** [comment]
Excellent, so I don't need to worry about skipping something -- so I just uploaded 5.18.

Hmmm, I think it's again time for someone to sit with Dick to clean up the TeXShop sources to slim them down. Like, `Resources/Shellscripts/TeXShop.app` is a full copy of TeXShop, surely we don't need to include those 90 MB with each copy of the source code ;-)

**Comment by mschmidt-name** [comment]
I raised this with him and he did a silent re-release of 5.18, removing `Resources/Shellscripts/TeXShop.app` and fixing a bug in the new code of `Sources/TSDocument-Jobs.m` that I noticed.

**Comment by fingolfin** [comment]
Yeah I also exchanged emails with him about it and pointed out a few other things that could be cleaned up for next time
