### ISSUE TITLE
GitHub Repository Latest Version Downloads?

### ISSUE THREAD

**Issue by uurazzle** [TeXShop/TeXShop#3]
Hi:

Not an issue, but a question. Will this GitHub repository contain the latest version like the recently released 5.27?

Or to get the latest releases you should always go to the website?

https://pages.uoregon.edu/koch/texshop/obtaining.html

The reason I ask, is many use automation tools like AutoPKG or Installomator to discover, download and install the latest versions of Mac software like TeXShop, etc Having an official site that will always have the latest release would be good to leverage with these tools.

**Comment by fingolfin** [comment]
This repository is an unofficial mirror, updated manually by me on occasion. The only official source is https://pages.uoregon.edu/koch/texshop/
